name: setup-aseprite-cli-action
description: GitHub Action to build and install the Aseprite CLI.
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - id: prepare
    run: bash ./prepare.sh
    env:
      NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.ACTION_REPOSITORY }}
      NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.ACTION_REF }}
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - id: cache
    uses: actions/cache@v2
    with:
      path: ${{ GITHUB.ACTION_PATH }}/build/bin
      key: neomura-setup-aseprite-cli-action-${{ GITHUB.REPOSITORY }}-${{ GITHUB.REF }}-${{ runner.os }}-${{ steps.prepare.outputs.sha }}
  - run: ./build.sh
    if: steps.cache.outputs.cache-hit != 'true'
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - run: ./install.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
