on: [push, pull_request]

jobs:
  test-first-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2025
        - windows-2025-vs2026
        - windows-2022
        - ubuntu-24.04
        - ubuntu-22.04
        - macos-15-intel
        - macos-26-intel
        - macos-15
    steps:
    - uses: actions/checkout@v7
    - id: prepare
      run: bash ./prepare.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - id: cache
      uses: actions/cache@v6
      with:
        path: clone/submodules/aseprite/aseprite/build/bin
        key: neomura-setup-aseprite-cli-action-${{ GITHUB.REPOSITORY }}-${{ GITHUB.REF }}-${{ matrix.os }}-${{ steps.prepare.outputs.sha }}
    - uses: ilammy/msvc-dev-cmd@v1
    - run: bash ./build.sh
    - run: bash ./install.sh
    - uses: actions/setup-node@v6
      with:
        node-version: '26.3'
        registry-url: 'https://registry.npmjs.org'
    - run: bash ./test.sh
  test-subsequent-run:
    needs: test-first-run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2025
        - windows-2025-vs2026
        - windows-2022
        - ubuntu-24.04
        - ubuntu-22.04
        - macos-15-intel
        - macos-26-intel
        - macos-15
    steps:
    - uses: actions/checkout@v7
    - id: prepare
      run: bash ./prepare.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - id: cache
      uses: actions/cache@v6
      with:
        path: clone/submodules/aseprite/aseprite/build/bin
        key: neomura-setup-aseprite-cli-action-${{ GITHUB.REPOSITORY }}-${{ GITHUB.REF }}-${{ matrix.os }}-${{ steps.prepare.outputs.sha }}
    - uses: ilammy/msvc-dev-cmd@v1
    - run: bash ./build.sh
    - run: bash ./install.sh
    - uses: actions/setup-node@v6
      with:
        node-version: '26.3'
        registry-url: 'https://registry.npmjs.org'
    - run: bash ./test.sh
